### ISSUE TITLE
Lib throws an error on identifier set to `undefined`

### ISSUE THREAD

**Issue by jcalixte** [bamlab/react-native-batch-push#37]
Hi!

When I want to unsubscribe a user to batch when he wants to logout, I try to set the `identifier` to `undefined` as typed by the library (the code calls the method `clearUserId`).

```ts
import { Batch, BatchUser } from "@bam.tech/react-native-batch";

class Notification {
  public constructor() {
    Batch.start();
  }

  public setUserId(id?: string): void {
    BatchUser.editor()
      .setIdentifier(id)
      .save();
  }

  public clearUserId(): void {
    this.setUserId();
  }
}

export const NotificationService = new Notification();
```

throws this error
![image](https://user-images.githubusercontent.com/3417063/74231320-a5602a80-4cc6-11ea-835e-512cac114c07.png)

When I set the identifier to `null` (as the [doc in Batch](https://doc.batch.com/android/custom-data/customid#choosing-a-unique-identifier) seems to define it), it works like a charm. But TypeScript is not happy : `Argument of type 'null' is not assignable to parameter of type 'string | undefined'.`

Does the .d.ts file need to be updated?

Thank you.

**Comment by Aure77** [comment]
Same issue on Android.
It's due to `ReadableNativeMap#getType` that throw an [NoSuchKeyException](https://github.com/facebook/react-native/blob/18a8c8580d0086355e0bcbddc956d61960326040/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeMap.java#L180) if value is undefined.

To fix this issue, this lib should check key existence (with `hasKey`) before using `getType`, or add a try/catch block on `NoSuchKeyException` and define as `null` in these case.
Or disallow using `undefined` & allow `null` in TS declaration.
